# Generated by Django 2.2.2 on 2019-11-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_mail',
            field=models.CharField(max_length=128),
        ),
    ]
